fix: handle fixup! correctly in commit-msg hook

diff --git a/misc/git-hooks/commit-msg b/misc/git-hooks/commit-msg
--- a/misc/git-hooks/commit-msg
+++ b/misc/git-hooks/commit-msg
@@ -2,29 +2,24 @@
 
 set -eu
 
-export tmp_file="$1.tmp"
-
-function rm_tmp_file {
-  rm -f "$tmp_file"
-}
-
-trap rm_tmp_file EXIT
-
 # Sanitize file first, by removing leading lines that are empty or start with a hash,
 # as `convco` currently does not do it automatically (but git will)
 # TODO: next release of convco should be able to do it automatically
-echo -n "" > "$tmp_file"
-while read -r line ; do
-  # skip any initial comments (possibly from previous run)
-  if [ -z "${body_detected:-}" ] && { [[ "$line" =~ ^#.*$ ]] || [ "$line" == "" ]; }; then
-    continue
-  fi
-  body_detected="true"
+MESSAGE="$(
+  while read -r line ; do
+    # skip any initial comments (possibly from previous run)
+    if [ -z "${body_detected:-}" ] && { [[ "$line" =~ ^#.*$ ]] || [ "$line" == "" ]; }; then
+      continue
+    fi
+    body_detected="true"
 
-  echo "$line" >> "$tmp_file"
-done < "$1"
+    echo "$line"
+  done < "$1"
+)"
 
-if ! convco check < "$tmp_file" ; then
+# convco fails on fixup!, so remove fixup! prefix
+MESSAGE="${MESSAGE#fixup! }"
+if ! convco check <<<"$MESSAGE" ; then
    >&2 echo "Please follow conventional commits(https://www.conventionalcommits.org)"
    >&2 echo "Use git recommit <args> to fix your commit"
   exit 1
