chore: time git commit checks in CI

diff --git a/misc/git-hooks/pre-commit b/misc/git-hooks/pre-commit
--- a/misc/git-hooks/pre-commit
+++ b/misc/git-hooks/pre-commit
@@ -201,7 +201,17 @@ function check_typos() {
 }
 export -f check_typos
 
-parallel ::: \
+tmpdir=$(mktemp --tmpdir -d XXXXX)
+trap 'rm -r $tmpdir' EXIT
+joblog="$tmpdir/joblog"
+
+if ! parallel \
+  --joblog "$joblog" \
+  --halt-on-error 1 \
+  --timeout 60 \
+  --load 500% \
+  --nice 15 \
+  ::: \
   check_semgrep_all \
   check_semgrep_log \
   check_nix \
@@ -212,3 +222,12 @@ parallel ::: \
   check_forbidden_dependencies \
   check_cargo_lock \
   check_typos
+then
+  >&2 echo "Some checks failed. Full job log:"
+  cat "$joblog"
+  exit 1
+else
+  if [ -n "$GIT_PRE_COMMIT_SHOW_STATS" ] ; then
+    cat "$joblog"
+  fi
+fi
