chore: change ldk-node-0 log name

diff --git a/scripts/dev/run-test/fm-run-test b/scripts/dev/run-test/fm-run-test
--- a/scripts/dev/run-test/fm-run-test
+++ b/scripts/dev/run-test/fm-run-test
@@ -46,7 +46,7 @@ on_error() {
   echo
   echo
   echo "## LOG LDK-0 NODE:"
-  { cat  "$FM_RUN_TEST_TMPDIR"/devimint-*/gatewayd-ldk-0/ldk_node/logs/ldk_node_latest.log || true; } | grep -v "Failed to retrieve fee rate estimates" || true
+  { cat  "$FM_RUN_TEST_TMPDIR"/devimint-*/gatewayd-ldk-0/ldk_node/ldk_node.log || true; } | grep -v "Failed to retrieve fee rate estimates" || true
   echo
   echo "## FAIL END $test_name$version_str."
 }
