chore: only print output of a test on failure

diff --git a/scripts/dev/run-test/fm-run-test b/scripts/dev/run-test/fm-run-test
--- a/scripts/dev/run-test/fm-run-test
+++ b/scripts/dev/run-test/fm-run-test
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -eo pipefail
+
 test_name="$1"
 shift 1
 
@@ -9,14 +11,22 @@ if [ -z "$test_name" ]; then
 fi
 
 version_str="${FM_RUN_TEST_VERSIONS:+ ($FM_RUN_TEST_VERSIONS)}"
-
-set -eo pipefail # pipefail must be set manually again
-trap 'echo "## FAILED: $test_name$version_str"' ERR
+out_path="$(mktemp --tmpdir fm-XXXXX)"
+export FM_TEST_NAME="$test_name"
 
 echo "## START: $test_name$version_str"
 
-export FM_TEST_NAME="$test_name"
+on_error() {
+  echo "## FAILED: $test_name$version_str; OUT:"
+  cat "$out_path"
+  echo "## FAILED: $test_name$version_str; END"
+}
 
-"$@" 2>&1 | ts -s
+on_exit() {
+    rm -Rf "$CARGO_BUILD_TARGET_DIR"
+}
+trap on_error ERR
+
+"$@" 2>&1 | ts -s > "$out_path"
 
 echo "## COMPLETE: $test_name$version_str"
